import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { createRestaurant, Restaurant } from '../api';
import './AddRestaurantForm.css'; // We'll create this CSS file next

const AddRestaurantForm: React.FC = () => {
  const [name, setName] = useState('');
  const [address, setAddress] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    const newRestaurant: Restaurant = {
      // ID will be generated by the backend
      id: '', 
      name: name,
      address: address,
    };

    try {
      await createRestaurant(newRestaurant);
      // Redirect to the restaurant list after successful creation
      navigate('/'); 
    } catch (err) {
      console.error('Error creating restaurant:', err);
      setError('Failed to create restaurant. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="add-restaurant-form-container">
      <h2>Add New Restaurant</h2>
      <form onSubmit={handleSubmit} className="add-restaurant-form">
        <div className="form-group">
          <label htmlFor="name">Restaurant Name:</label>
          <input
            type="text"
            id="name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
          />
        </div>
        <div className="form-group">
          <label htmlFor="address">Address:</label>
          <input
            type="text"
            id="address"
            value={address}
            onChange={(e) => setAddress(e.target.value)}
            required
          />
        </div>
        <button type="submit" disabled={loading}>
          {loading ? 'Adding...' : 'Add Restaurant'}
        </button>
        {error && <p className="error-message">{error}</p>}
      </form>
    </div>
  );
};

export default AddRestaurantForm;